definitions:
  controllers.createProductRequest:
    properties:
      color:
        type: string
      description:
        type: string
      name:
        type: string
      price:
        type: number
      type:
        type: string
      weight:
        type: number
    required:
    - color
    - description
    - name
    - price
    - type
    - weight
    type: object
  controllers.errorResponse:
    properties:
      message:
        type: string
      success:
        type: boolean
    type: object
  controllers.productSuccessResponse1:
    properties:
      data:
        $ref: '#/definitions/models.Product'
      success:
        type: boolean
    type: object
  controllers.productSuccessResponse2:
    properties:
      data:
        items:
          $ref: '#/definitions/models.Product'
        type: array
      success:
        type: boolean
    type: object
  controllers.updateProductRequest:
    properties:
      Weight:
        type: number
      color:
        type: string
      description:
        type: string
      name:
        type: string
      price:
        type: number
      type:
        type: string
    type: object
  models.Product:
    properties:
      color:
        type: string
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      price:
        type: number
      type:
        type: string
      updated_at:
        type: string
      weight:
        type: number
    type: object
info:
  contact: {}
paths:
  /product:
    get:
      consumes:
      - application/json
      description: Should get all products successfully
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.productSuccessResponse2'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.errorResponse'
      summary: Get all products
      tags:
      - Product
    post:
      consumes:
      - application/json
      description: Should create a new product in the database successfully
      parameters:
      - description: Body Json
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controllers.createProductRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/controllers.productSuccessResponse1'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.errorResponse'
      summary: Create a new product
      tags:
      - Product
  /product/{id}:
    delete:
      consumes:
      - application/json
      description: Should delete a product by his id successfully
      parameters:
      - description: Id Product
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.productSuccessResponse1'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.errorResponse'
      summary: Delete a product
      tags:
      - Product
    get:
      consumes:
      - application/json
      description: Should get a product by his id successfully
      parameters:
      - description: Id Product
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.productSuccessResponse1'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.errorResponse'
      summary: Get a product by his id
      tags:
      - Product
    put:
      consumes:
      - application/json
      description: Should update an existing product in the database successfully
      parameters:
      - description: Id Product
        in: path
        name: id
        required: true
        type: string
      - description: Body Json
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controllers.updateProductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.productSuccessResponse1'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.errorResponse'
      summary: Update a product
      tags:
      - Product
swagger: "2.0"
